apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  source:
    repoURL: https://stevehipwell.github.io/helm-charts/
    chart: nexus3
    targetRevision: "5.19.0"
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: gp3
          size: 2Gi

        service:
          type: ClusterIP

        ingress:
          enabled: false

        properties:
          - nexus.datastore.enabled=true
          - nexus.loadAsOSS=true
          - nexus-context-path=/nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true