apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: "10.6.0"
    helm:
      values: |
        persistence:
          enabled: false
          storageClass: gp3
          size: 5Gi

        service:
          type: ClusterIP

        # Enable bundled PostgreSQL (nonprod)
        postgresql:
          enabled: false
          persistence:
            enabled: false
            storageClass: gp3
            size: 1Gi

        sonarProperties:
          sonar.web.context: /sonar
          sonar.core.serverBaseURL: https://https://qj6jvlfmgh.execute-api.us-east-1.amazonaws.com/sonar

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true