apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: "2026.1.0"
    helm:
      values: |
        monitoringPasscode: "abdo-monitor"

        community:
          enabled: true

        sonarWebContext: /sonar

        sonarProperties:
          sonar.core.serverBaseURL: https://qj6jvlfmgh.execute-api.us-east-1.amazonaws.com/sonar

        service:
          type: ClusterIP

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true