apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ingress-nlb-tgb
  namespace: ingress-nginx
spec:
  serviceRef:
    name: ingress-nginx-controller
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:575108933009:targetgroup/nonprod-ingress-tg/d2294fec1830f3fa
  targetType: ip

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  namespace: default
spec:
  ingressClassName: nginx
  
  rules:
  - http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 80