apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-properties
  namespace: nexus
data:
  nexus.properties: |
    nexus.datastore.enabled=true
    nexus.loadAsOSS=true
    nexus-context-path=/nexus